language: bash

os:
- linux

env:
  - PYVER=
  - PYVER=3.7
  - PYVER=3.6
  - PYVER=3.5
  - PYVER=3.2
  - PYVER=2.7

services:
  - docker

script:
- |
  if [[ "$TRAVIS_OS_NAME" == 'linux' && -n "$PYVER" ]]; then
    printf "FROM python:${PYVER}-cli-alpine\nRUN apk add --update make\nWORKDIR /code\nENTRYPOINT []\nCMD [\"make\"]" > Dockerfile
    docker build --tag tester:${PYVER}-alpine .
    docker run -it -v `pwd`:/code tester:${PYVER}-alpine composer install --dev --prefer-dist
    docker run -it -v `pwd`:/code tester:${PYVER}-alpine
  fi

notifications:
  email:
    on_success: never